"use client";

import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings({
  en: {
    home: "Home",
    main: "Main",
    login: "Sign in",
    logout: "Log out",
    updated: "updated",
    lastupdated: "Last update",
    chartCategory: "CHART",
    chartSection: "Chart",
    nationalaccounts: "National Accounts",
    budget: "Budget",
    unemployment: "Unemployment",
    inflation: "Inflation",
    tradebalance: "Trade Balance",
    oilGas: "Oil, Gas",
    gas: "Gas",
    banks: "Banks",
    comsumerloans: "Comsumer Loans",
    hajjandumrah: "Hajj And Umrah",
    comsumerspending: "Comsumer Spending",
    petrochemical: "PetroChemical",
    insurance: "Insurance",
    cement: "Cement",
    medcare: "Med Care",
    marketanalytics: "Market Analytics",
    telecommunication: "Telecommunication",
    industrial: "Industrial",
    travelandaviation: "Travel And Aviation",
    oilsector: "Oil Sector(Billion)",
    nonOilgovernmentsector: "Non-Oil government sector",
    nonOilsector: "Non-Oil sector ",
    GD: "gd",
    grossdomesticproductatcurrentprices:
      "Gross Domestic Product at Current Prices",
    privatefinalconsumptionexpenditure:
      "Private Final Consumption Expenditure (Billion)",
    changeinstock: "Change in Stock",
    grossfixedcapitalformation: "Gross Fixed Capital Formation",
    totalexcludingnettaxesonproducts: "Total excluding Net Taxes on products",
    nettaxesonproducts: "Net taxes on Products",
    totalexcludingimportduties: "Total excluding Import Duties",
    expenditureongdp: "Expenditure on GDP",
    atcurrentprices: "At Current Prices (Billion)",



    exportsofgoodsandservices: "Exports of Goods & Services",
    importsofgoodsandservices: "Imports of Goods & Services",
    totalexpenditureongdp: "Total Expenditure on GDP",

    atconstantprices: "At Constant Prices( base year 2010)",
 
  
    about: "About Us",
    tourism: "Tourism",
    contactus: "Contact Us",
    unitbillion: "",
    emailaddress: "Email Address",
    password: "Password",
    loginSubmit: "Submit",
    signinTitle: "Sign in",
    copylink: "Copy Link",
    link: "Copy link",
    embedLink: "Embed Link",
    embedArgaamLink: "Embed Argaam Link",
    copyLinkAlertText: "URL copied",
    copyLinkIframeText: "Embed Iframe copied to clipboard",
    compareLabel: "Compare",
    share: "Share Link",
    excel: "Download Excel",
    download: "Download Excel",
    imageDownload: "Image",
    copyright: "Copyright © {0}",
    searchPlaceholder: "Search",
    aboutUs: "About",
    notesTableDataFiscal: "Date/Fiscal Period",
    notesTableChartName: "Chart Name",
    notesTableAr: "Notes Ar",
    notesTableEn: "Notes En",
    notesTableAction: "Actions",
    notesFormDateFiscal: "Date/Fiscal Period",
    notesFormNoteEn: "Notes English",
    notesFormNoteAr: "Notes Arabic",
    notesAddNewBtn: "Add New",
    notesSaveBtn: "Save",
    notesUpdateBtn: "Update",
    notesCancelBtn: "Cancel",
    notesFieldRequiredMsg: "Kindly fill all the required fields!",
    notesDeleteMsg: "Are you sure . Want to delete this note ?",
    notesDeleteYes: "Yes",
    notesDeleteNo: "No",
    notesChartName: "Chart",
    noRecordFound: "No Record Found",
    notesToolTip: "Notes",
    fullView: "Full View",
    notFoundTitle: "Page Not Found",
    notFoundMessage: "Sorry, the page you are looking for could not be found.",
    notFoundGoToHome: "Go to Home",
    nodata: "No Data",
    privacyPolicy: "Privacy Policy",
    settings: "Settings",
    homeAll: "All",
    tryAgain: "Try Again",
    someThingWrong: "Something went wrong",
    categoryAll: "All Data",
    argaamToolsSelective: "Selective Data",
    rank: "Rank",
    company: "Company",
    includingAramco: "Including Aramco",
    notesEconomicIndicatorLbl: "Field",
    pleaseSelect: "Please Select",
    changeInTenYears: "Change in 10 Years: ",
    customEmbed: "Custom Embed",
    selectedColor: "Selected Color",
    removeColor: "Remove Color",
    addColor: "Add Color",
    selectColor: "Select Color",
    iframeWidthLabel: "Width (%)",
    iframeHeightLabel: "Height (px)",
    charts: "Charts",
    homeHistoricalDataTitle: "Historical data of the Saudi economy",
    homeHistoricalDataSubTitle: "Historical data of the Saudi economy and various sectors since 1970",
    footerSocialMedia: "Social Media",
    searchTitlePage: "Pages",
    searchTitleSection: "Sections",
    searchTitleCharts: "Charts",
    argaamWebsite: "Argaam Website",
    faq: "FAQ",
    footerNeedHelp: "Need Help?",
    footerContactDetails: "Contact Details",
    footerQuickLinks: "Quick links",
    footerTell: "Tel: ",
    footerFax: "Fax: ",
    footerAddress: "Riyadh, Saudi Arabia 11596",
    footerEmail: "Email: ",
    sectorBreadcrumbHome: "Home",
    sourceLabel: "Source: ",
    footerHotLine: "Riyadh, Kingdom of Saudi Arabia",
    anyQuestion: "Any Questions",
    argaam: "Argaam",
    requestsubmitted: "Request Submitted",
    firstname: "First Name",
    pleaseenterfirstname: "Please enter first name",
    lastname: "Last Name",
    pleaseenterlastname: "Please enter last name",

    pleaseenteremail: "Please enter your email",
    pleaseentervalidemail: "Please enter a valid email",
    phonenumber: "Phone Number",
    entervalidphone: "Please enter a valid phone number",
    invalidphonenoerror: "please enter your phone number correctly as (54*******)",
    companyfield: "Company",
    pleaseentercompany: "Please enter company",
    jobtitle: "Job Title",
    additionalcmmnts: "Additional Comments",
    requestconfirm:
      "By submitting this form, I agree to the collection and use of my personal data by Argaam Investment in accordance with the",
    requestconfirm2: "Privacy Policy.",
    submit: "Submit",
    alreadycustomer: "Already a customer?",
    logintocharts: "Login to Argaam Macro",

    countrycode: "Country Code",

    yougotfreetrial:
      "Congratulations, you got a free trial. For more information please contact the Sales Team by {0} or {1}",
    yougotfreetrialwith5:
      "Congratulations, you got a free trial. You can use the analysis services to download 10 Excel files & images during the free trial. For more information, please contact the Sales Team by {0} or {1}",
    youtrialexpired:
      "Sorry, your free trial is over, please contact the Sales Team by {0} or {1}",
    trialIsNotActivate: "Your trial is not activated",
    salesemail: "sales.team@argaam.com",
    email: "email",
    companyphone: "(+966 92000 7759)",
    excelDownloadError:
      "Sorry, you have exceeded the number of times for downloading ",
    freeuserexcelerror:
      "Sorry, downloading files is available for Argaam Plus subscribers only. For more information, please contact the Sales Team",
    analystuserexcelerror:
      "Sorry, downloading files is available only for Free Trial, Analyst or Full Package subscribers. For more information, please contact the Sales Team",
    analystuserimageerror:
      "Sorry, downloading images is available only for Free Trial, Analyst or Full Package subscribers. For more information, please contact the Sales Team",
    freeusershareerror:
      "Sorry, sharing Charts is available for Argaam Plus subscribers only. For more information, please contact the Sales Team",
    analystusershareerror:
      "Sorry, sharing charts is available only for Free Trial, Analyst or Full Package subscribers. For more information, please contact the Sales Team",

    ok: "OK",
    requestproductdetails: "Request Product",

    freeuserimageerror:
      "Sorry, downloading images is available for Argaam Plus subscribers only. For more information, please contact the Sales Team",
    commonErrorAlert: "An error occured. Please try again.",
    requestProductHeaderLbl: "Request Product",
    freeTrialLabel: "Free Trial",
    availableForAll: "Free",
    loginAboutUs: "Login",
    discoverArgaamMacroTitle: "Discover Argaam Macro Features ",
    clicktoexpand: "Click to Expand",
    whatCanYouFindInMacro: "What can you find in Argaam Macro?",
    whatIsNewInMacro: "What’s new in Argaam Macro?",
    bannerDesc:
      "Argaam Macro provides comprehensive economic data and statistics on the Saudi economy through simplified charts that cover all sectors, fields, and available historical periods, with some items extending over more than 50 years. The platform also offers necessary comparisons, growth indicators, and explanatory notes. ",
    bannerDesc2:
      "The Macro platform incorporates in detail all aspects related to the macroeconomics, such as inflation, labor forces, unemployment, GDP, the budget, the trade balance, as well as population, and real estate, electricity, industry, water sector indicators, among other data on the Saudi economy.",
    privacyPolicyFooter: "Privacy Policy",
    termsconditions: "Terms & Conditions",
    loginMobileHeader: "Login",
    powereddevelopedby: "Powered and developed by {0} - {1}",
    allrightsreserved: "All Rights Reserved",
    argaamdotcom: "argaam.com",
    dashboardExpDataValue1: "+35",
    dashboardExpDataText1: "Specialized pages",
    dashboardExpDataValue2: "+1000",
    dashboardExpDataText2: "Charts covering all available items",
    dashboardExpDataValue3: "+50 Years",
    dashboardExpDataText3: "Statistical data",
    dashboardExpDataValue4: "+∞",
    dashboardExpDataText4: "Updates On data and new sectors ",
    dashboardExpDataValue5: "Exclusive",
    dashboardExpDataText5: "Data and ratios",
    dashbaordExpTab1: "Investment Summary",
    dashbaordExpTab2: "Company Size & Ranking",
    dashbaordExpTab3: "Data and Analysis",
    dashbaordExpTab4: "Financial Data",
    dashbaordExpTab5: "Financial Ratios",
    dashbaordExpTab6: "Segment & Geo Analysis",
    dashbaordExpTab7: "Sector Ratios",
    dashboardExpRightTitle:
      "The must start insights that summarizes companies history",
    dashboardExpRightDesc1:
      "Argaam Macro enables users to measure the historical performance of a stock since listing on a quarterly or annual basis. It also displays historical cash dividends, total yield, and valuation multiples, allowing for comparisons with competitors and over different time periods.",
    dashboardExpRightDesc2:
      "This section shows the size and ranking of a company compared to market peers through key financial ratios and data.",
    dashboardExpRightDesc3:
      "It includes exclusive analytical data and ratios by Argaam, such as petrochemical product prices, company stakes, profit margins, average selling prices in cement companies, as well as evaluations of banks and calculated prices. These are presented historically and across various time periods.",
    dashboardExpRightDesc4:
      "This section presents the most important historical financial data for the company spanning over 20 years in different time periods. Users have the ability to compare this data peers.",
    dashboardExpRightDesc5:
      "This section highlights key financial ratios for companies, banks, and REITs, covering various periods. Users can compare these ratios with those of peers.",
    dashboardExpRightDesc6:
      "This section presents the sectoral and geographic analysis of the key financial data of companies, banks, and REITs historically and across different time periods.",
    dashboardExpRightDesc7:
      "It reviews key data and ratios on the sector level, where the company, bank, or REIT operates. It aims to assist investors in identifying the key factors influencing the company's future and in measuring its performance and size within the sector.",

    writeatexthere:
      "Write your question here and one of our specialists will respond",
    send: "Send",
    clear: "Clear",
    susbmittedsuccess: "Submitted successfully",
    pageDescHover: "Page Summary"






  },
  ar: {
    categoryAll: "جميع البيانات",
    argaamToolsSelective: "بيانات مختارة",
    searchPlaceholder: "بحث",
    main: "الرئيسية",
    login: "تسجيل الدخول",
    logout: "تسجيل خروج",
    updated: "محدث",
    lastupdated: "آخر تحديث",
    chartCategory: "رسما بيانيا",
    chartSection: "رسما بيانيا",
    oilsector: "إجمالي القطاع النفطي(مليار)",
    nonOilgovernmentsector: "القطاع الخاص غير النفطي",
    nonOilsector: "القطاع الحكومي غير النفطي",
    gdp: "الناتج المحلي الإجمالي",
    grossdomesticproductatcurrentprices: " بالأسعار الجارية  (مليار)",
    privatefinalconsumptionexpenditure:
      "الانفاق الاستهلاكي النهائي الخاص( مليار)",
    changeinstock: "التغير بالمخزون",
    grossfixedcapitalformation: "إجمالي تكوين رأس المال الثابت",
    totalexcludingnettaxesonproducts:
      "الإجمالي ماعدا صافي الضرائب على المنتجات (مليار)",
    nettaxesonproducts: "صافي الضرائب على المنتجات ",
    totalexcludingimportduties: "الإجمالي ما عدا رسوم الإستيراد ",
    expenditureongdp: "لإنفاق على الناتج المحلي الإجمالي ",
    atcurrentprices: "بالأسعار الجارية(مليار)",



    exportsofgoodsandservices: "صادرات البضائع والخدمات ",
    importsofgoodsandservices: "واردات البضائع والخدمات ",
    totalexpenditureongdpexpenditureongdp:
      "الإنفاق على الناتج المحلي الإجمالي بالأسعار الثابتة",
    atconstantprices: "( سنه الاساس 2010) (مليار)",


  

   
    totalexpenditureongdp: "اجمالي الانفاق على الناتج",
    about: "معلومات عنا",
    home: "الرئيسية",
    nationalaccounts: "الحسابات القومية",
    budget: "ميزانية",
    unemployment: "البطالة",
    inflation: "تضخم",
    tradebalance: "الميزان التجاري",
    oilGas: "النفط والغاز",
    banks: "البنوك",
    comsumerloans: "القروض الاستهلاكية",
    hajjandumrah: "الحج والعمرة",
    comsumerspending: "مصروفات المستهلك",
    petrochemical: "تأمين",
    insurance: "الصحة",
    cement: "الاسمنت",
    medcare: "صناعي",
    marketanalytics: "تحليلات السوق",
    telecommunication: "ااتصالات",
    industrial: "صناعي",
    travelandaviation: "السفر والطيران",
    tourism: "السياحة",
    contactus: "تواصل معنا",
    unitbillion: "",
    emailaddress: "عنوان البريد الإلكتروني",
    password: "كلمة المرور",
    loginSubmit: "موافق",
    signinTitle: "تسجيل الدخول",
    copylink: "نسخ الرابط",
    link: "الرابط",
    embedLink: "رابط الإدراج",
    embedArgaamLink: "تضمين رابط أرقام",
    copyLinkAlertText: "تم نسخ الرابط",
    copyLinkIframeText: "تم نسخ تضمين Iframe إلى الحافظة",
    compareLabel: "يقارن",
    share: "مشاركة",
    excel: "تحميل اكسيل",
    download: "تحميل اكسيل",
    imageDownload: "صورة",
    copyright:
      "حقوق النشر والتأليف © 2024",
    aboutUs: "حول",
    notesTableDataFiscal: "التاريخ / الفترة المالية",
    notesTableChartName: "اسم المخطط",
    notesTableAr: "الملاحظات بالعربية",
    notesTableEn: "الملاحظات بالإنجليزية",
    notesTableAction: "الإجراءات",
    notesFormDateFiscal: "التاريخ / الفترة المالية",
    notesFormNoteEn: "الملاحظات بالإنجليزية",
    notesFormNoteAr: "الملاحظات بالعربية",
    notesAddNewBtn: "إضافة جديدة",
    notesSaveBtn: "حفظ",
    notesUpdateBtn: "تحديث",
    notesCancelBtn: "إلغاء",
    notesFieldRequiredMsg: "يرجى ملء جميع الحقول المطلوبة!",
    notesDeleteMsg: "هل أنت متأكد؟ هل ترغب في حذف هذه الملاحظة؟",
    notesDeleteYes: "نعم",
    notesDeleteNo: "لا",
    notesChartName: "جدول",
    noRecordFound: "لا يوجد سجلات",
    notesToolTip: "ملحوظات",
    fullView: "عرض كامل",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundMessage: "عذرًا، لا يمكن العثور على الصفحة التي تبحث عنها.",
    notFoundGoToHome: "الذهاب إلى الصفحة الرئيسية",
    nodata: "لايوجد بيانات",
    privacyPolicy: "سياسة الخصوصية",
    settings: "إعدادات",
    homeAll: "الجميع",
    tryAgain: "حاول ثانية",
    someThingWrong: "هناك خطأ ما",
    rank: "الترتيب",
    company: "الشركة",
    includingAramco: "مع ارامكو",
    notesEconomicIndicatorLbl: "مجال",
    pleaseSelect: "الرجاء التحديد",
    changeInTenYears: "نسبة التغير 10 سنوات: ",
    customEmbed: "تضمين مخصص",
    selectedColor: "اللون المحدد",
    removeColor: "إزالة اللون",
    addColor: "أضف اللون",
    selectColor: "إختر لون",
    iframeWidthLabel: "العرض (%)",
    iframeHeightLabel: "الارتفاع (بكسل)",
    charts: "رسماً بيانياً",
    homeHistoricalDataTitle: "بيانات تاريخية للاقتصاد السعودي",
    homeHistoricalDataSubTitle: "بيانات تاريخية للاقتصاد السعودي والقطاعات المختلفة منذ عام 1970",
    footerSocialMedia: "وسائل التواصل الاجتماعي",
    searchTitlePage: "الصفحات",
    searchTitleSection: "الأقسام",
    searchTitleCharts: "الرسوم البيانية",
    argaamWebsite: "موقع أرقام",
    faq: "الأسئلة الشائعة",
    footerNeedHelp: "هل تحتاج إلى مساعدة؟",
    footerContactDetails: "تفاصيل الاتصال",
    footerQuickLinks: "روابط سريعة",
    footerTell: "هاتف: ",
    footerFax: "فاكس: ",
    footerAddress: "العنوان: الرياض، المملكة العربية السعودية 11596",
    footerEmail: "البريد الإلكتروني: ",
    sectorBreadcrumbHome: "الرئيسية",
    sourceLabel: "المصدر: ",
    footerHotLine: "الرياض، المملكة العربية السعودية",
    anyQuestion: "لديك سؤال",
    argaam: "أرقام",
    requestsubmitted: "تم تقديم الطلب ",
    firstname: "الاسم الأول",
    pleaseenterfirstname: "من فضلك أدخل الاسم الأول",
    lastname: "اسم العائلة",
    pleaseenterlastname: "من فضلك أدخل اسم العائلة",

    pleaseenteremail: "من فضلك أدخل البريد الإلكتروني",
    pleaseentervalidemail: "يرجى إدخال البريد الإلكتروني الصحيح",
    phonenumber: "رقم التليفون",
    entervalidphone: "من فضلك أدخل رقم الجوال",
    invalidphonenoerror: "من فضلك ادخل رقم الهاتف الصحيح مثل(*******54)",
    companyfield: "الشركة",
    pleaseentercompany: "من فضلك أدخل اسم الشركة",
    jobtitle: "المسمى الوظيفي",
    additionalcmmnts: "تعليقات إضافية",
    requestconfirm:
      "من خلال إرسال هذا النموذج، فإني أوافق على جمع واستخدام بياناتي الشخصية من قبل أرقام الاستثمارية وفقاً",
    requestconfirm2: "لسياسة الخصوصية",
    submit: "إرسال",
    alreadycustomer: "لديك حساب؟",
    logintocharts: "الدخول إلى أرقام ماكرو",

    countrycode: "رمز الدولة",


    yougotfreetrial:
      "تهانينا، لقد حصلت على تجربة مجانية، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات من خلال {0} أو {1}",
    yougotfreetrialwith5: `تهانينا، لقد حصلت على تجربة مجانية، مع إمكانية استخدام خدمات التحليل بتحميل 10 ملفات اكسل وصور أثناء التجربة المجانية، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات من خلال {0} أو {1}`,
    youtrialexpired:
      "عفواً، لقد استنفذت مدة التجربة المجانية، يرجى التواصل مع فريق المبيعات من خلال {0} أو {1}",
    trialIsNotActivate: "لم يتم تفعيل النسخة التجريبية الخاصة بك",
    salesemail: "sales.team@argaam.com",
    email: "البريد الإلكتروني",
    companyphone: "(+966 92000 7759)",
    excelDownloadError: "عفواً، لقد تخطيت عدد مرات التحميل المتاحة",
    freeuserexcelerror:
      "عذراً، تحميل الملفات متاح لمشتركي باقات أرقام بلس فقط، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات",
    analystuserexcelerror:
      "عفواً، تحميل الملفات متاح فقط للمشتركين بالتجربة المجانية، باقة المحللين أو الباقة الكاملة، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات",
    analystuserimageerror: 'عفواً، تحميل الصور متاح فقط للمشتركين بالتجربة المجانية، باقة المحللين أو الباقة الكاملة، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات',
    freeusershareerror:
      "عذراً، مشاركة تشارت متاح لمشتركي باقات أرقام بلس فقط، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات",
    analystusershareerror:
      "عفواً، مشاركة تشارت متاحة فقط للمشتركين بالتجربة المجانية، باقة المحللين أو الباقة الكاملة، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات",
    ok: "موافق",
    requestproductdetails: "اطلب المنتج",
    freeuserimageerror: 'عفواً، تحميل الصور متاح لمشتركي باقات أرقام بلس فقط، ولمزيد من المعلومات يرجى التواصل مع فريق المبيعات',
    commonErrorAlert: "حدث خطأ. حاول مرة اخرى.",
    requestProductHeaderLbl: "اطلب المنتج",
    freeTrialLabel: "نسخة تجريبية",
    availableForAll: "متاحة للجميع",
    loginAboutUs: "تسجيل الدخول",
    discoverArgaamMacroTitle: "اكتشف ميزات وخصائص أرقام ماكرو",
    clicktoexpand: "انقر للتكبير",
    whatCanYouFindInMacro: "ماذا يمكنك أن تجد في أرقام ماكرو؟",
    whatIsNewInMacro: "ما الجديد في أرقام ماكرو؟",
    bannerDesc:
      "تقدم أرقام ماكرو بيانات ومؤشرات اقتصادية شاملة عن الاقتصاد السعودي عبر رسوم بيانية مبسطة تشمل جميع القطاعات والمجالات والفترات التاريخية المتاحة، والتي تصل في بعض البنود إلى أكثر من 50 عاماً، مع تقديم المقارنات اللازمة ومؤشرات النمو والملاحظات التوضيحية.",
    bannerDesc2:
      "تغطي منصة ماكرو كل البنود المتعلقة بالاقتصاد الكلي بكل تفاصيلها مثل التضخم، وقوى العمل، والبطالة، والناتج الإجمالي، والميزانية، والميزان التجاري، إضافة إلى السكان، والمؤشرات العقارية، وقطاعات الكهرباء، والصناعة، والمياه، وكل ما هو متاح من بيانات عن الاقتصاد السعودي.",
    privacyPolicyFooter: "سياسة الخصوصية",
    termsconditions: "الشروط والأحكام",
    loginMobileHeader: "تسجيل الدخول",
    powereddevelopedby: `بإدارة وتطوير {0} {1}`,
    allrightsreserved: `${"جميع الحقوق محفوظة"} ${"Argaam.com"}`,
    argaamdotcom: "أرقام الاستثمارية ",


    dashboardExpDataValue1: "+35",
    dashboardExpDataText1: "صفحة متخصصة ",
    dashboardExpDataValue2: "+1000",
    dashboardExpDataText2: "رسم بياني يغطي كل البنود المتاحة ",
    dashboardExpDataValue3: " +50 سنة ",
    dashboardExpDataText3: "بيانات إحصائية ",
    dashboardExpDataValue4: "+∞",
    dashboardExpDataText4: "إضافة مستمرة للبيانات والقطاعات الجديدة ",
    dashboardExpDataValue5: "حصرية ",
    dashboardExpDataText5: "بيانات ومؤشرات حصرية ",
    dashbaordExpTab1: "ملخص الاستثمار",
    dashbaordExpTab2: "حجم وترتيب الشركة",
    dashbaordExpTab3: "بيانات وتحليلات",
    dashbaordExpTab4: "البيانات المالية",
    dashbaordExpTab5: "المؤشرات المالية",
    dashbaordExpTab6: "التحليل القطاعي والجغرافي",
    dashbaordExpTab7: "معلومات عامة للقطاع",
    dashboardExpRightTitle: "يجب أن تبدأ الأفكار التي تلخص تاريخ الشركات",
    dashboardExpRightDesc1:
      "تمكن أرقام ماكرو المستخدمين من خلال ملخص الاستثمار قياس الأداء التاريخي للسهم منذ الإدراج بشكل ربعي وسنوي، كما تعرض التوزيعات النقدية التاريخية والعائد الكلي ومضاعفات التقييم مع إمكانية مقارنتها مع المنافسين واستعراضها بفترات زمنية مختلفة.",
    dashboardExpRightDesc2:
      "تستعرض حجم وترتيب الشركة بالسوق مقارنة بالشركات المماثلة من خلال أهم البيانات والمؤشرات المالية.",
    dashboardExpRightDesc3:
      "تشمل بيانات ومؤشرات تحليلية حصرية لأرقام، مثل أسعار المنتجات البتروكيماوية وحصص الشركات وهوامش الربحية، ومتوسطات أسعار البيع في شركات الأسمنت، وتقييمات البنوك والأسعار المحسوبة بشكل تاريخي وبفترات زمنية مختلفة.",
    dashboardExpRightDesc4:
      "تستعرض أهم البيانات المالية للشركة بشكل تاريخي لأكثر من ٢٠ سنة بفترات زمنية مختلفة، مع إمكانية مقارنتها مع الشركات المماثلة.",
    dashboardExpRightDesc5:
      "تستعرض أهم المؤشرات المالية للشركات والبنوك وصناديق الريت، وفقاً للفترات المالية المختلفة، مع إمكانية مقارنتها مع الشركات المماثلة لها.",
    dashboardExpRightDesc6:
      "عرض بيانات التحليل القطاعي والجغرافي لأهم البيانات المالية للشركات والبنوك وصناديق الريت، بشكل تاريخي ولفترات زمنية مختلفة.",
    dashboardExpRightDesc7:
      "تستعرض أهم البيانات والمؤشرات على مستوى القطاع الذي تعمل من خلاله الشركة، البنك او صناديق الريت، لمساعدة المستثمرين في تحديد أهم العوامل المؤثرة على مستقبل الشركة وكذلك قياس أداء الشركة وحجمها على مستوى القطاع.",

    writeatexthere: "اكتب سؤالك هنا وسيقوم أحد المختصين بالرد",
    send: "إرسال",
    clear: "مسح",
    susbmittedsuccess: "تم الإرسال بنجاح",
    pageDescHover: "ملخص الصفحة"

  },
});
